// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbjjhrqromuwzmwfocht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiampocnFyb211d3ptd2ZvY2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzQ4OTksImV4cCI6MjA1OTExMDg5OX0.tdYeEvkRjZOd_9F17E3NSB89t0tVeI-1cumNcvKrPGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);